server:
  ssl:
    enabled: true
    key-store: classpath:keystore/truststore.p12
    key-store-type: PKCS12
    key-store-password: changeit
    protocol: TLS
    enabled-protocols: TLSv1.2
    client-auth: need
    #trust store location
    trust-store: classpath:keystore/truststore.p12
    trust-store-type: PKCS12
    #trust store password
    trust-store-password: changeit
  port: 9443