quartz:
  using: spring
spring:
  quartz:
    job-store-type: jdbc # job存储方式：jdbc持久存储，memory内存存储
    wait-for-jobs-to-complete-on-shutdown: true  # 程序结束时会等待quartz相关的job结束
    overwrite-existing-jobs: true # QuartzScheduler启动时更新己存在的Job
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: scheduler # scheduler的实例名
            instanceId: AUTO # scheduler的ID
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: qrtz_ # 表示数据库中相关表是qrtz_开头的
            useProperties: false # true表示JDBCJobStore，JobDataMaps中的所有值都将是“字符串”，因此可以将其存储为名称 - 值对，而不是以BLOB列的序列化形式存储更复杂的对象
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool # 线程池
            threadCount: 10 # 线程数
            threadPriority: 5 # 线程优先级
            threadsInheritContextClassLoaderOfInitializingThread: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: <<username>>
    password: <<password>>
  flyway:
    baseline-on-migrate: true
    baseline-description: <<Flyway Baseline>>
    enabled: true
    check-location: true
    locations: classpath:db/migrations
    validate-on-migrate: true